// <auto-generated />
using GudangApp.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GudangApp.Api.Data.Migrations
{
    [DbContext(typeof(GudangStoreContext))]
    partial class GudangStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("GudangApp.Api.Entities.Gudang", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nama");

                    b.HasKey("Id");

                    b.ToTable("gudang", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
